### PR TITLE
Add windows installation compatibility

### PR DESCRIPTION
**Pull request by asimon-1**

### CODE REVIEW

**Comment by myint** [comment]
Thanks! I can merge this in once the functionality in the existing `eradicate` script is somehow merged into this.

**Comment by CAM-Gerlach** [comment]
@asimon-1 @myint At least running under pre-commit, the current version (2.0.0) of Eradicate is still broken and unusable for me on Windows (failing on run with error `Executable `C:UsersC.` not found`). Furthermore, it appears it relies on ancient and deprecated `distutils` functionality that will be removed and thus stop working for everyone in the Python version after next, which this PR resolves. Could you outline the blocker(s) to getting this critical PR merged? Thanks!

**Comment by sobolevn** [comment]
Hi everyone! 👋 
Especially @CAM-Gerlach :)

Do you still need this PR? In case you do, please rebase / recreate it.
I will be more than happy to merge it and add Windows CI.

**Comment by CAM-Gerlach** [comment]
Hi @sobolevn ; cool to see you here! Haven't been really following development of this so not 100% sure the specific blocker is here, but given there are no apparent conflicts (assuming GitHub is reporting that correctly) it would seem that the changes are still needed, and if it just needs a rebase any maintainer should be able to trigger it either manually or with this option in the main repo settings page:

image

If further non-trivial changes are needed perhaps I could make them as suggestions if possible, though at that point might be worth just remaking the PR to fix/clean up some things and add the CIs. Not 100% sure I'll have the bandwidth but I can try to give it a shot.

**Comment by CAM-Gerlach** [comment]
Also, I couldn't resist the opportunity considering our typical respective roles in the past, haha...

image

**Comment by sobolevn** [comment]
@CAM-Gerlach this is very funny 😆 

I cannot change the project settings. But I can re-open this PR. I think that GitHub does the rebase automatically in this case.

There are some conflicts for sure, for example: https://github.com/myint/eradicate/blob/master/setup.py#L8

**Comment by asimon-1** [comment]
Hi all - thanks for reopening this! I haven't been involved with the guts of python distribution in some time, so it'd be better if someone else handled the rebase conflicts.

I remember this being a pretty small change so hopefully it will be easy to address.

**Comment by CAM-Gerlach** [comment]
> I cannot change the project settings.

If you're the lead maintainer, that's a longer-term issue—you might want to consider asking @myint to move the project to a GitHub org with shared ownership to reduce bus factor.

> But I can re-open this PR. I think that GitHub does the rebase automatically in this case.

Hmm, I don't think so but it will re-run the checks.

> There are some conflicts for sure, for example: [master/setup.py#L8](https://github.com/myint/eradicate/blob/master/setup.py?rgh-link-date=2023-03-01T11%3A36%3A24Z#L8)

Hmm, in that case GitHub is likely screwing up and saying it doesn't because the PR is too old...yeah, best to create a new one. I'll add it to my queue and take a look if I get the time, given @asimon-1 is okay with it, unless you get to it first.

**Comment by asimon-1** [comment]
All yours

**Comment by myint** [comment]
@sobolevn Sure, that works for me.

**Comment by sobolevn** [comment]
@myint can you please first send a transfer request for my personal account?
This way I won't need to add you to the org. Because "create repo" permission is required for an org transfer.

I will transfer it to the org.

Thanks a lot! 👍

**Comment by myint** [comment]
Screen Shot 2023-03-02 at 07 24 29

**Comment by sobolevn** [comment]
@myint I've removed my fork, please try again.

**Comment by myint** [comment]
Done:

> Repository transfer to sobolevn requested

**Comment by sobolevn** [comment]
🎉 

New home is here :)

**Comment by sobolevn** [comment]
@myint please check your admin permissions. Does it work? Anything else we have to do? :)

**Comment by CAM-Gerlach** [comment]
Great, thanks @myint and @sobolevn ! With the additional motivation of your effort here, I'll try to take a look at this next week.

And @sobolevn I had no idea all this time that you were the guy behind the famous WeMake! I've actually used your linter config and (at least part of) your style guide on some of my repos.

**Comment by sobolevn** [comment]
@CAM-Gerlach awesome to hear that! I know that it might be way too strict sometimes, but I see great results of it tutoring my students.

I've enabled the "rebase" button for this repo. Testing it out.

**Comment by myint** [comment]
@sobolevn Things look good to me. Thanks!

**Comment by sobolevn** [comment]
Sorry for the extra noise!

**Comment by sobolevn** [comment]
I got a "yes" from PyCQA: https://mail.python.org/archives/list/code-quality@python.org/thread/33SZLUQZJFUPK3OAP7DJCIHTTDEOSSNG/

@myint what do you think? :)
Do you approve it?

**Comment by sobolevn** [comment]
I will close this issue, because 2.3 with Windows support was just released, but I am still waiting for @myint's response about the project transfer :)

**Comment by myint** [comment]
@sobolevn Moving it to PyCQA sounds great to me!

**Comment by sobolevn** [comment]
Done, I hope for the final time :)

**Pull request closed without merging**
